name: build-and-release

on:
  workflow_dispatch

jobs:
  check_main:
    runs-on: ubuntu-latest
    steps:
      - name: Release from main
        if: github.ref == 'refs/heads/main'
        run: echo '::notice ::Building and uploading release'
      - name: No release
        if: github.ref != 'refs/heads/main'
        run: echo '::warning ::Release can only be run from the main branch!' && exit 1

  build_package:
    runs-on: ubuntu-latest
    needs: [check_main]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
          installer-parallel: true
      - name: Build package
        run: poetry build
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: dist

  release_python:
    runs-on: ubuntu-latest
    needs: [build_package]
    environment:
      name: pypi
      url: https://pypi.org/p/thants
    permissions:
      id-token: write
    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.13.0
